// backend/src/catalog/buildCatalogSql.ts
import { expandCatalog, validateCatalog, type CurriculumCatalog } from './catalog.js';

export const CATALOG_MIGRATION_PATH = new URL(
  '../../../supabase/migrations/20260927090100_gdpt2018_catalog.sql',
  import.meta.url,
);

const q = (value: string) => `'${value.replace(/'/g, "''")}'`;

export function buildCatalogMigrationSql(catalog: CurriculumCatalog): string {
  const errors = validateCatalog(catalog);
  if (errors.length > 0) throw new Error(`Invalid catalog:\n${errors.join('\n')}`);

  const { version, subjects, tracks, legacy } = catalog;
  const removeList = `array[${legacy.remove.map(q).join(',')}]`;
  const lines: string[] = [];

  lines.push(
    '-- GENERATED by backend/scripts/generate-catalog-migration.ts from supabase/catalog/gdpt2018.json.',
    '-- Do not edit by hand: change the JSON and rerun the script.',
    '',
    '-- 1. Legacy per-level subject rows → one subject per continuous curriculum subject.',
  );
  for (const [from, to] of Object.entries(legacy.rename)) {
    lines.push(
      `update public.subjects set slug = ${q(to)} where slug = ${q(from)} and not exists (select 1 from public.subjects where slug = ${q(to)});`,
    );
  }
  lines.push(
    '',
    'do $$',
    'declare',
    '  r record;',
    '  n int;',
    'begin',
    '  for r in',
    "    select c.table_name from information_schema.columns c",
    "    where c.table_schema = 'public' and c.column_name = 'subject_id' and c.table_name <> 'subjects'",
    '  loop',
    "    execute format('select count(*) from public.%I x join public.subjects s on s.id = x.subject_id where s.slug = any ($1)', r.table_name)",
    `      into n using ${removeList};`,
    '    if n > 0 then',
    `      raise exception 'Legacy subject % is still referenced by %', ${removeList}, r.table_name;`,
    '    end if;',
    '  end loop;',
    'end $$;',
    `delete from public.subjects where slug = any (${removeList});`,
    '',
    '-- 2. Subjects with bilingual names, icon and accent.',
    'insert into public.subjects (slug, name_en, name_vi, icon, accent_color, sort_order) values',
  );
  lines.push(
    subjects
      .map((s, i) => `  (${q(s.slug)}, ${q(s.name_en)}, ${q(s.name_vi)}, ${q(s.icon)}, ${q(s.accent_color.toLowerCase())}, ${i})`)
      .join(',\n'),
  );
  lines.push(
    'on conflict (slug) do update set',
    '  name_en = excluded.name_en, name_vi = excluded.name_vi, icon = excluded.icon,',
    '  accent_color = excluded.accent_color, sort_order = excluded.sort_order;',
    '',
    '-- 3. Curriculum version.',
    'insert into public.curriculum_versions (code, name_vi, issued_by, effective_from, source_ref, status) values',
    `  (${q(version.code)}, ${q(version.name_vi)}, ${q(version.issued_by)}, ${q(version.effective_from)}, ${q(JSON.stringify(version.source_ref))}::jsonb, 'active')`,
    'on conflict (code) do update set name_vi = excluded.name_vi, issued_by = excluded.issued_by,',
    '  effective_from = excluded.effective_from, source_ref = excluded.source_ref;',
    '',
    '-- 4. One catalog row per subject and grade.',
    'insert into public.subject_grade_catalog (curriculum_version_id, subject_id, grade, curriculum_role, sort_order, source_ref)',
    'select v.id, s.id, r.grade, r.curriculum_role, r.sort_order, v.source_ref',
    'from (values',
  );
  lines.push(expandCatalog(catalog).map((r) => `  (${q(r.slug)}, ${r.grade}, ${q(r.role)}, ${r.sort_order})`).join(',\n'));
  lines.push(
    ') as r(slug, grade, curriculum_role, sort_order)',
    'join public.subjects s on s.slug = r.slug',
    `join public.curriculum_versions v on v.code = ${q(version.code)}`,
    'on conflict (curriculum_version_id, subject_id, grade) do update set',
    '  curriculum_role = excluded.curriculum_role, sort_order = excluded.sort_order, active = true;',
    '',
    '-- 5. Subject tracks.',
    'insert into public.subject_tracks (subject_id, slug, name_en, name_vi, grades, sort_order)',
    'select s.id, t.slug, t.name_en, t.name_vi, t.grades::int[], t.sort_order',
    'from (values',
  );
  lines.push(
    tracks
      .map((t, i) => `  (${q(t.subject)}, ${q(t.slug)}, ${q(t.name_en)}, ${q(t.name_vi)}, ${q(`{${t.grades.join(',')}}`)}, ${i})`)
      .join(',\n'),
  );
  lines.push(
    ') as t(subject, slug, name_en, name_vi, grades, sort_order)',
    'join public.subjects s on s.slug = t.subject',
    'on conflict (subject_id, slug) do update set',
    '  name_en = excluded.name_en, name_vi = excluded.name_vi, grades = excluded.grades, sort_order = excluded.sort_order;',
    '',
  );

  return lines.join('\n');
}
