-- GENERATED by backend/scripts/generate-catalog-migration.ts from supabase/catalog/gdpt2018.json.
-- Do not edit by hand: change the JSON and rerun the script.

-- 1. Legacy per-level subject rows → one subject per continuous curriculum subject.
update public.subjects set slug = 'informatics-technology' where slug = 'primary-informatics-technology' and not exists (select 1 from public.subjects where slug = 'informatics-technology');
update public.subjects set slug = 'nature-society' where slug = 'primary-nature-society' and not exists (select 1 from public.subjects where slug = 'nature-society');
update public.subjects set slug = 'science' where slug = 'primary-science' and not exists (select 1 from public.subjects where slug = 'science');
update public.subjects set slug = 'natural-science' where slug = 'lower-natural-science' and not exists (select 1 from public.subjects where slug = 'natural-science');
update public.subjects set slug = 'technology' where slug = 'lower-technology' and not exists (select 1 from public.subjects where slug = 'technology');

do $$
declare
  r record;
  n int;
begin
  for r in
    select c.table_name from information_schema.columns c
    where c.table_schema = 'public' and c.column_name = 'subject_id' and c.table_name <> 'subjects'
  loop
    execute format('select count(*) from public.%I x join public.subjects s on s.id = x.subject_id where s.slug = any ($1)', r.table_name)
      into n using array['primary-math','lower-math','lower-informatics','primary-stem-exploration','lower-stem-projects'];
    if n > 0 then
      raise exception 'Legacy subject % is still referenced by %', array['primary-math','lower-math','lower-informatics','primary-stem-exploration','lower-stem-projects'], r.table_name;
    end if;
  end loop;
end $$;
delete from public.subjects where slug = any (array['primary-math','lower-math','lower-informatics','primary-stem-exploration','lower-stem-projects']);

-- 2. Subjects with bilingual names, icon and accent.
insert into public.subjects (slug, name_en, name_vi, icon, accent_color, sort_order) values
  ('vietnamese', 'Vietnamese', 'Tiếng Việt', 'Aa', '#dc2626', 0),
  ('literature', 'Literature', 'Ngữ văn', '✎', '#b91c1c', 1),
  ('math', 'Mathematics', 'Toán', '∑', '#2563eb', 2),
  ('foreign-language-1', 'Foreign Language 1', 'Ngoại ngữ 1', 'EN', '#0284c7', 3),
  ('foreign-language-2', 'Foreign Language 2', 'Ngoại ngữ 2', 'L2', '#0369a1', 4),
  ('ethics', 'Ethics', 'Đạo đức', '♡', '#db2777', 5),
  ('civic-education', 'Civic Education', 'Giáo dục công dân', '⚖', '#be185d', 6),
  ('economic-law-education', 'Economic and Law Education', 'Giáo dục kinh tế và pháp luật', '§', '#9d174d', 7),
  ('nature-society', 'Nature and Society', 'Tự nhiên và Xã hội', '◎', '#059669', 8),
  ('science', 'Science', 'Khoa học', '◌', '#0891b2', 9),
  ('natural-science', 'Natural Science', 'Khoa học tự nhiên', '⌬', '#0e7490', 10),
  ('history-geography', 'History and Geography', 'Lịch sử và Địa lí', '⌛', '#b45309', 11),
  ('history', 'History', 'Lịch sử', '⏳', '#92400e', 12),
  ('geography', 'Geography', 'Địa lí', '⊕', '#a16207', 13),
  ('physics', 'Physics', 'Vật lí', '⚛', '#7c3aed', 14),
  ('chemistry', 'Chemistry', 'Hoá học', '⚗', '#0d9488', 15),
  ('biology', 'Biology', 'Sinh học', '❁', '#65a30d', 16),
  ('informatics-technology', 'Informatics and Technology', 'Tin học và Công nghệ', '⌨', '#4338ca', 17),
  ('informatics', 'Informatics', 'Tin học', '</>', '#16a34a', 18),
  ('technology', 'Technology', 'Công nghệ', '⚙', '#475569', 19),
  ('physical-education', 'Physical Education', 'Giáo dục thể chất', '⚑', '#ea580c', 20),
  ('national-defence', 'National Defence and Security Education', 'Giáo dục quốc phòng và an ninh', '★', '#57534e', 21),
  ('arts', 'Arts (Music, Fine Arts)', 'Nghệ thuật (Âm nhạc, Mĩ thuật)', '♫', '#c026d3', 22),
  ('music', 'Music', 'Âm nhạc', '♪', '#a21caf', 23),
  ('fine-arts', 'Fine Arts', 'Mĩ thuật', '✿', '#9333ea', 24),
  ('experiential-activities', 'Experiential Activities', 'Hoạt động trải nghiệm', '✦', '#d97706', 25),
  ('experiential-career', 'Experiential and Career Guidance Activities', 'Hoạt động trải nghiệm, hướng nghiệp', '➚', '#c2410c', 26),
  ('local-education', 'Local Education Content', 'Nội dung giáo dục của địa phương', '⌂', '#7e22ce', 27),
  ('ethnic-language', 'Ethnic Minority Language', 'Tiếng dân tộc thiểu số', '◇', '#0f766e', 28)
on conflict (slug) do update set
  name_en = excluded.name_en, name_vi = excluded.name_vi, icon = excluded.icon,
  accent_color = excluded.accent_color, sort_order = excluded.sort_order;

-- 3. Curriculum version.
insert into public.curriculum_versions (code, name_vi, issued_by, effective_from, source_ref, status) values
  ('gdpt2018-vbhn-2022', 'Chương trình giáo dục phổ thông 2018 (văn bản hợp nhất Thông tư 32/2018, 20/2021, 13/2022)', 'Bộ Giáo dục và Đào tạo', '2018-12-26', '{"title":"Văn bản hợp nhất Chương trình giáo dục phổ thông","organization_or_author":"Bộ Giáo dục và Đào tạo","url_or_document_id":"https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf"}'::jsonb, 'active')
on conflict (code) do update set name_vi = excluded.name_vi, issued_by = excluded.issued_by,
  effective_from = excluded.effective_from, source_ref = excluded.source_ref;

-- 4. One catalog row per subject and grade.
insert into public.subject_grade_catalog (curriculum_version_id, subject_id, grade, curriculum_role, sort_order, source_ref)
select v.id, s.id, r.grade, r.curriculum_role, r.sort_order, v.source_ref
from (values
  ('vietnamese', 1, 'required', 0),
  ('vietnamese', 2, 'required', 0),
  ('vietnamese', 3, 'required', 0),
  ('vietnamese', 4, 'required', 0),
  ('vietnamese', 5, 'required', 0),
  ('literature', 6, 'required', 1),
  ('literature', 7, 'required', 1),
  ('literature', 8, 'required', 1),
  ('literature', 9, 'required', 1),
  ('literature', 10, 'required', 1),
  ('literature', 11, 'required', 1),
  ('literature', 12, 'required', 1),
  ('math', 1, 'required', 2),
  ('math', 2, 'required', 2),
  ('math', 3, 'required', 2),
  ('math', 4, 'required', 2),
  ('math', 5, 'required', 2),
  ('math', 6, 'required', 2),
  ('math', 7, 'required', 2),
  ('math', 8, 'required', 2),
  ('math', 9, 'required', 2),
  ('math', 10, 'required', 2),
  ('math', 11, 'required', 2),
  ('math', 12, 'required', 2),
  ('foreign-language-1', 1, 'optional', 3),
  ('foreign-language-1', 2, 'optional', 3),
  ('foreign-language-1', 3, 'required', 3),
  ('foreign-language-1', 4, 'required', 3),
  ('foreign-language-1', 5, 'required', 3),
  ('foreign-language-1', 6, 'required', 3),
  ('foreign-language-1', 7, 'required', 3),
  ('foreign-language-1', 8, 'required', 3),
  ('foreign-language-1', 9, 'required', 3),
  ('foreign-language-1', 10, 'required', 3),
  ('foreign-language-1', 11, 'required', 3),
  ('foreign-language-1', 12, 'required', 3),
  ('foreign-language-2', 6, 'optional', 4),
  ('foreign-language-2', 7, 'optional', 4),
  ('foreign-language-2', 8, 'optional', 4),
  ('foreign-language-2', 9, 'optional', 4),
  ('foreign-language-2', 10, 'optional', 4),
  ('foreign-language-2', 11, 'optional', 4),
  ('foreign-language-2', 12, 'optional', 4),
  ('ethics', 1, 'required', 5),
  ('ethics', 2, 'required', 5),
  ('ethics', 3, 'required', 5),
  ('ethics', 4, 'required', 5),
  ('ethics', 5, 'required', 5),
  ('civic-education', 6, 'required', 6),
  ('civic-education', 7, 'required', 6),
  ('civic-education', 8, 'required', 6),
  ('civic-education', 9, 'required', 6),
  ('economic-law-education', 10, 'elective_choice', 7),
  ('economic-law-education', 11, 'elective_choice', 7),
  ('economic-law-education', 12, 'elective_choice', 7),
  ('nature-society', 1, 'required', 8),
  ('nature-society', 2, 'required', 8),
  ('nature-society', 3, 'required', 8),
  ('science', 4, 'required', 9),
  ('science', 5, 'required', 9),
  ('natural-science', 6, 'required', 10),
  ('natural-science', 7, 'required', 10),
  ('natural-science', 8, 'required', 10),
  ('natural-science', 9, 'required', 10),
  ('history-geography', 4, 'required', 11),
  ('history-geography', 5, 'required', 11),
  ('history-geography', 6, 'required', 11),
  ('history-geography', 7, 'required', 11),
  ('history-geography', 8, 'required', 11),
  ('history-geography', 9, 'required', 11),
  ('history', 10, 'required', 12),
  ('history', 11, 'required', 12),
  ('history', 12, 'required', 12),
  ('geography', 10, 'elective_choice', 13),
  ('geography', 11, 'elective_choice', 13),
  ('geography', 12, 'elective_choice', 13),
  ('physics', 10, 'elective_choice', 14),
  ('physics', 11, 'elective_choice', 14),
  ('physics', 12, 'elective_choice', 14),
  ('chemistry', 10, 'elective_choice', 15),
  ('chemistry', 11, 'elective_choice', 15),
  ('chemistry', 12, 'elective_choice', 15),
  ('biology', 10, 'elective_choice', 16),
  ('biology', 11, 'elective_choice', 16),
  ('biology', 12, 'elective_choice', 16),
  ('informatics-technology', 3, 'required', 17),
  ('informatics-technology', 4, 'required', 17),
  ('informatics-technology', 5, 'required', 17),
  ('informatics', 6, 'required', 18),
  ('informatics', 7, 'required', 18),
  ('informatics', 8, 'required', 18),
  ('informatics', 9, 'required', 18),
  ('informatics', 10, 'elective_choice', 18),
  ('informatics', 11, 'elective_choice', 18),
  ('informatics', 12, 'elective_choice', 18),
  ('technology', 6, 'required', 19),
  ('technology', 7, 'required', 19),
  ('technology', 8, 'required', 19),
  ('technology', 9, 'required', 19),
  ('technology', 10, 'elective_choice', 19),
  ('technology', 11, 'elective_choice', 19),
  ('technology', 12, 'elective_choice', 19),
  ('physical-education', 1, 'required', 20),
  ('physical-education', 2, 'required', 20),
  ('physical-education', 3, 'required', 20),
  ('physical-education', 4, 'required', 20),
  ('physical-education', 5, 'required', 20),
  ('physical-education', 6, 'required', 20),
  ('physical-education', 7, 'required', 20),
  ('physical-education', 8, 'required', 20),
  ('physical-education', 9, 'required', 20),
  ('physical-education', 10, 'required', 20),
  ('physical-education', 11, 'required', 20),
  ('physical-education', 12, 'required', 20),
  ('national-defence', 10, 'required', 21),
  ('national-defence', 11, 'required', 21),
  ('national-defence', 12, 'required', 21),
  ('arts', 1, 'required', 22),
  ('arts', 2, 'required', 22),
  ('arts', 3, 'required', 22),
  ('arts', 4, 'required', 22),
  ('arts', 5, 'required', 22),
  ('arts', 6, 'required', 22),
  ('arts', 7, 'required', 22),
  ('arts', 8, 'required', 22),
  ('arts', 9, 'required', 22),
  ('music', 10, 'elective_choice', 23),
  ('music', 11, 'elective_choice', 23),
  ('music', 12, 'elective_choice', 23),
  ('fine-arts', 10, 'elective_choice', 24),
  ('fine-arts', 11, 'elective_choice', 24),
  ('fine-arts', 12, 'elective_choice', 24),
  ('experiential-activities', 1, 'required_activity', 25),
  ('experiential-activities', 2, 'required_activity', 25),
  ('experiential-activities', 3, 'required_activity', 25),
  ('experiential-activities', 4, 'required_activity', 25),
  ('experiential-activities', 5, 'required_activity', 25),
  ('experiential-career', 6, 'required_activity', 26),
  ('experiential-career', 7, 'required_activity', 26),
  ('experiential-career', 8, 'required_activity', 26),
  ('experiential-career', 9, 'required_activity', 26),
  ('experiential-career', 10, 'required_activity', 26),
  ('experiential-career', 11, 'required_activity', 26),
  ('experiential-career', 12, 'required_activity', 26),
  ('local-education', 6, 'required', 27),
  ('local-education', 7, 'required', 27),
  ('local-education', 8, 'required', 27),
  ('local-education', 9, 'required', 27),
  ('local-education', 10, 'required', 27),
  ('local-education', 11, 'required', 27),
  ('local-education', 12, 'required', 27),
  ('ethnic-language', 1, 'optional', 28),
  ('ethnic-language', 2, 'optional', 28),
  ('ethnic-language', 3, 'optional', 28),
  ('ethnic-language', 4, 'optional', 28),
  ('ethnic-language', 5, 'optional', 28),
  ('ethnic-language', 6, 'optional', 28),
  ('ethnic-language', 7, 'optional', 28),
  ('ethnic-language', 8, 'optional', 28),
  ('ethnic-language', 9, 'optional', 28),
  ('ethnic-language', 10, 'optional', 28),
  ('ethnic-language', 11, 'optional', 28),
  ('ethnic-language', 12, 'optional', 28)
) as r(slug, grade, curriculum_role, sort_order)
join public.subjects s on s.slug = r.slug
join public.curriculum_versions v on v.code = 'gdpt2018-vbhn-2022'
on conflict (curriculum_version_id, subject_id, grade) do update set
  curriculum_role = excluded.curriculum_role, sort_order = excluded.sort_order, active = true;

-- 5. Subject tracks.
insert into public.subject_tracks (subject_id, slug, name_en, name_vi, grades, sort_order)
select s.id, t.slug, t.name_en, t.name_vi, t.grades::int[], t.sort_order
from (values
  ('informatics', 'ict', 'Applied Informatics', 'Tin học ứng dụng', '{10,11,12}', 0),
  ('informatics', 'cs', 'Computer Science', 'Khoa học máy tính', '{10,11,12}', 1),
  ('technology', 'industrial', 'Industrial Technology', 'Công nghệ công nghiệp', '{10,11,12}', 2),
  ('technology', 'agricultural', 'Agricultural Technology', 'Công nghệ nông nghiệp', '{10,11,12}', 3)
) as t(subject, slug, name_en, name_vi, grades, sort_order)
join public.subjects s on s.slug = t.subject
on conflict (subject_id, slug) do update set
  name_en = excluded.name_en, name_vi = excluded.name_vi, grades = excluded.grades, sort_order = excluded.sort_order;
