-- Glossary: a starter set of bilingual terms for the THPT subjects (Informatics first).
-- Content is data: re-running is safe (one term per subject + English name).

create unique index if not exists terms_subject_term_en_key on public.terms (subject_id, lower(term_en));

with src (slug, term_en, term_vi, pos, def_en, def_vi, ex_en, ex_vi) as (
  values
  -- Informatics
  ('informatics', 'algorithm', 'thuật toán', 'noun', 'A finite sequence of clear steps that solves a problem.', 'Dãy hữu hạn các bước rõ ràng để giải một bài toán.', 'Binary search is an efficient search algorithm.', 'Tìm kiếm nhị phân là một thuật toán tìm kiếm hiệu quả.'),
  ('informatics', 'time complexity', 'độ phức tạp thời gian', 'noun', 'How the running time of an algorithm grows with the size of its input.', 'Mức tăng thời gian chạy của thuật toán theo kích thước dữ liệu vào.', 'The time complexity of binary search is O(log n).', 'Độ phức tạp thời gian của tìm kiếm nhị phân là O(log n).'),
  ('informatics', 'recursion', 'đệ quy', 'noun', 'A technique where a function calls itself on a smaller version of the problem.', 'Kĩ thuật trong đó hàm tự gọi lại chính nó với bài toán nhỏ hơn.', 'Factorial can be computed with recursion.', 'Có thể tính giai thừa bằng đệ quy.'),
  ('informatics', 'variable', 'biến', 'noun', 'A named place in memory that stores a value which can change.', 'Vùng nhớ có tên, lưu một giá trị có thể thay đổi.', 'The variable total stores the sum so far.', 'Biến total lưu tổng đã tính được.'),
  ('informatics', 'data type', 'kiểu dữ liệu', 'noun', 'The kind of value a variable holds, such as integer, real number or string.', 'Loại giá trị mà biến lưu, như số nguyên, số thực hay xâu.', 'In Python, 3.5 has the float data type.', 'Trong Python, 3.5 có kiểu dữ liệu float.'),
  ('informatics', 'loop', 'vòng lặp', 'noun', 'A statement that repeats a block of code while a condition holds or for each item.', 'Câu lệnh lặp lại một khối lệnh khi điều kiện còn đúng hoặc với từng phần tử.', 'A for loop prints the numbers from 1 to 10.', 'Vòng lặp for in ra các số từ 1 đến 10.'),
  ('informatics', 'conditional statement', 'câu lệnh rẽ nhánh', 'noun', 'A statement that runs different code depending on whether a condition is true.', 'Câu lệnh thực hiện các lệnh khác nhau tuỳ điều kiện đúng hay sai.', 'An if statement checks whether a number is even.', 'Câu lệnh if kiểm tra một số có chẵn hay không.'),
  ('informatics', 'function', 'hàm', 'noun', 'A named block of code that performs a task and can return a value.', 'Khối lệnh có tên, thực hiện một công việc và có thể trả về giá trị.', 'The function area(r) returns the area of a circle.', 'Hàm area(r) trả về diện tích hình tròn.'),
  ('informatics', 'parameter', 'tham số', 'noun', 'A variable in a function definition that receives a value when the function is called.', 'Biến trong định nghĩa hàm, nhận giá trị khi hàm được gọi.', 'In def square(x), x is a parameter.', 'Trong def square(x), x là tham số.'),
  ('informatics', 'list', 'danh sách', 'noun', 'An ordered collection of values accessed by index.', 'Tập hợp có thứ tự các giá trị, truy cập theo chỉ số.', 'scores = [8, 9, 7] is a list of three numbers.', 'scores = [8, 9, 7] là danh sách gồm ba số.'),
  ('informatics', 'array', 'mảng', 'noun', 'A fixed-size sequence of elements of the same type stored next to each other.', 'Dãy các phần tử cùng kiểu, kích thước cố định, lưu liên tiếp.', 'An array of 100 integers stores the test scores.', 'Mảng 100 số nguyên lưu điểm kiểm tra.'),
  ('informatics', 'string', 'xâu kí tự', 'noun', 'A sequence of characters, such as a word or sentence.', 'Dãy các kí tự, như một từ hay một câu.', '"SciPal" is a string of six characters.', '"SciPal" là xâu gồm sáu kí tự.'),
  ('informatics', 'sorting', 'sắp xếp', 'noun', 'Arranging items in a chosen order, such as ascending.', 'Đặt các phần tử theo một thứ tự, ví dụ tăng dần.', 'Bubble sort is a simple sorting algorithm.', 'Sắp xếp nổi bọt là một thuật toán sắp xếp đơn giản.'),
  ('informatics', 'binary search', 'tìm kiếm nhị phân', 'noun', 'Searching a sorted list by repeatedly halving the part that may hold the target.', 'Tìm trong dãy đã sắp xếp bằng cách liên tục chia đôi phần có thể chứa giá trị cần tìm.', 'Binary search finds a name in a sorted list of 1000 in about 10 steps.', 'Tìm kiếm nhị phân tìm một tên trong 1000 tên đã sắp xếp chỉ khoảng 10 bước.'),
  ('informatics', 'linear search', 'tìm kiếm tuần tự', 'noun', 'Checking items one by one until the target is found or the list ends.', 'Kiểm tra lần lượt từng phần tử đến khi tìm thấy hoặc hết dãy.', 'Linear search works even on an unsorted list.', 'Tìm kiếm tuần tự dùng được cả với dãy chưa sắp xếp.'),
  ('informatics', 'bug', 'lỗi chương trình', 'noun', 'A mistake in a program that makes it behave wrongly.', 'Sai sót trong chương trình khiến nó chạy không đúng.', 'An off-by-one bug skipped the last item.', 'Một lỗi lệch một đơn vị đã bỏ qua phần tử cuối.'),
  ('informatics', 'debugging', 'gỡ lỗi', 'noun', 'Finding and fixing mistakes in a program.', 'Tìm và sửa lỗi trong chương trình.', 'Printing variables is a simple way of debugging.', 'In giá trị biến là cách gỡ lỗi đơn giản.'),
  ('informatics', 'database', 'cơ sở dữ liệu', 'noun', 'An organised collection of data that can be stored, searched and updated.', 'Tập hợp dữ liệu có tổ chức, có thể lưu trữ, tìm kiếm và cập nhật.', 'The school keeps student records in a database.', 'Nhà trường lưu hồ sơ học sinh trong cơ sở dữ liệu.'),
  ('informatics', 'primary key', 'khoá chính', 'noun', 'A field whose value uniquely identifies each record in a table.', 'Trường có giá trị xác định duy nhất mỗi bản ghi trong bảng.', 'Student ID is the primary key of the Students table.', 'Mã học sinh là khoá chính của bảng HocSinh.'),
  ('informatics', 'query', 'truy vấn', 'noun', 'A request to retrieve or change data in a database.', 'Yêu cầu lấy ra hoặc thay đổi dữ liệu trong cơ sở dữ liệu.', 'A SQL query lists the students in class 11A.', 'Một truy vấn SQL liệt kê học sinh lớp 11A.'),
  ('informatics', 'network', 'mạng máy tính', 'noun', 'Computers and devices connected to share data and resources.', 'Các máy tính và thiết bị kết nối để chia sẻ dữ liệu và tài nguyên.', 'The school computer lab is a local area network.', 'Phòng máy của trường là một mạng cục bộ.'),
  ('informatics', 'IP address', 'địa chỉ IP', 'noun', 'A number that identifies a device on a network.', 'Dãy số xác định một thiết bị trong mạng.', '192.168.1.10 is a private IP address.', '192.168.1.10 là một địa chỉ IP riêng.'),
  ('informatics', 'encryption', 'mã hoá', 'noun', 'Turning data into a secret form so only people with the key can read it.', 'Biến đổi dữ liệu thành dạng bí mật để chỉ người có khoá mới đọc được.', 'HTTPS uses encryption to protect passwords.', 'HTTPS dùng mã hoá để bảo vệ mật khẩu.'),
  ('informatics', 'artificial intelligence', 'trí tuệ nhân tạo', 'noun', 'Computer systems that perform tasks that normally need human intelligence.', 'Hệ thống máy tính làm được những việc vốn cần trí thông minh của con người.', 'Artificial intelligence can recognise handwriting.', 'Trí tuệ nhân tạo có thể nhận dạng chữ viết tay.'),
  ('informatics', 'binary', 'hệ nhị phân', 'noun', 'The number system with only two digits, 0 and 1, used by computers.', 'Hệ đếm chỉ gồm hai chữ số 0 và 1, được máy tính sử dụng.', 'The number 5 is 101 in binary.', 'Số 5 viết trong hệ nhị phân là 101.'),
  ('informatics', 'byte', 'byte', 'noun', 'A unit of data made of 8 bits.', 'Đơn vị dữ liệu gồm 8 bit.', 'One English letter usually takes one byte.', 'Một chữ cái tiếng Anh thường chiếm một byte.'),
  -- Math
  ('math', 'function', 'hàm số', 'noun', 'A rule that gives each input exactly one output.', 'Quy tắc cho mỗi giá trị của biến đúng một giá trị tương ứng.', 'y = 2x + 1 is a linear function.', 'y = 2x + 1 là một hàm số bậc nhất.'),
  ('math', 'derivative', 'đạo hàm', 'noun', 'The instantaneous rate of change of a function.', 'Tốc độ biến thiên tức thời của hàm số.', 'The derivative of x² is 2x.', 'Đạo hàm của x² là 2x.'),
  ('math', 'integral', 'tích phân', 'noun', 'A measure of accumulated quantity, such as the area under a curve.', 'Đại lượng tích luỹ, như diện tích dưới một đường cong.', 'The integral of 2x from 0 to 1 equals 1.', 'Tích phân của 2x từ 0 đến 1 bằng 1.'),
  ('math', 'limit', 'giới hạn', 'noun', 'The value a function or sequence approaches.', 'Giá trị mà hàm số hay dãy số dần tiến tới.', 'The limit of 1/n as n grows is 0.', 'Giới hạn của 1/n khi n tăng vô hạn là 0.'),
  ('math', 'equation', 'phương trình', 'noun', 'A statement that two expressions are equal, often with an unknown.', 'Đẳng thức giữa hai biểu thức, thường chứa ẩn.', 'x² − 4 = 0 is a quadratic equation.', 'x² − 4 = 0 là một phương trình bậc hai.'),
  ('math', 'inequality', 'bất phương trình', 'noun', 'A statement comparing two expressions with <, >, ≤ or ≥.', 'Mệnh đề so sánh hai biểu thức bằng <, >, ≤ hoặc ≥.', 'Solve the inequality 2x > 6.', 'Giải bất phương trình 2x > 6.'),
  ('math', 'sequence', 'dãy số', 'noun', 'An ordered list of numbers.', 'Danh sách các số được sắp theo thứ tự.', '2, 4, 6, 8 is an arithmetic sequence.', '2, 4, 6, 8 là một cấp số cộng.'),
  ('math', 'probability', 'xác suất', 'noun', 'A number from 0 to 1 measuring how likely an event is.', 'Số từ 0 đến 1 đo khả năng xảy ra của một biến cố.', 'The probability of rolling a 6 is 1/6.', 'Xác suất gieo được mặt 6 chấm là 1/6.'),
  ('math', 'vector', 'vectơ', 'noun', 'A quantity with both magnitude and direction.', 'Đại lượng có cả độ lớn và hướng.', 'The vector AB points from A to B.', 'Vectơ AB có hướng từ A đến B.'),
  ('math', 'logarithm', 'lôgarit', 'noun', 'The power to which a base must be raised to give a number.', 'Số mũ cần nâng cơ số lên để được một số cho trước.', 'log₂ 8 = 3 because 2³ = 8.', 'log₂ 8 = 3 vì 2³ = 8.'),
  ('math', 'mean', 'số trung bình', 'noun', 'The sum of the values divided by how many there are.', 'Tổng các giá trị chia cho số giá trị.', 'The mean of 4, 6 and 8 is 6.', 'Số trung bình của 4, 6 và 8 là 6.'),
  ('math', 'permutation', 'hoán vị', 'noun', 'An arrangement of objects in a particular order.', 'Một cách sắp xếp các đối tượng theo thứ tự.', 'There are 6 permutations of three letters.', 'Ba chữ cái có 6 hoán vị.'),
  -- Physics
  ('physics', 'velocity', 'vận tốc', 'noun', 'The rate of change of position, with direction.', 'Tốc độ thay đổi vị trí, có kèm hướng.', 'The car moves at a velocity of 20 m/s north.', 'Xe chạy với vận tốc 20 m/s hướng bắc.'),
  ('physics', 'acceleration', 'gia tốc', 'noun', 'The rate of change of velocity.', 'Tốc độ thay đổi của vận tốc.', 'Free-fall acceleration near Earth is about 9.8 m/s².', 'Gia tốc rơi tự do gần mặt đất khoảng 9,8 m/s².'),
  ('physics', 'force', 'lực', 'noun', 'A push or pull that can change an object''s motion.', 'Tác dụng đẩy hoặc kéo làm thay đổi chuyển động của vật.', 'Force is measured in newtons.', 'Lực được đo bằng niutơn.'),
  ('physics', 'momentum', 'động lượng', 'noun', 'Mass times velocity of an object.', 'Tích của khối lượng và vận tốc của vật.', 'Momentum is conserved in a collision.', 'Động lượng được bảo toàn trong va chạm.'),
  ('physics', 'kinetic energy', 'động năng', 'noun', 'Energy an object has because it is moving.', 'Năng lượng vật có do chuyển động.', 'Kinetic energy equals ½mv².', 'Động năng bằng ½mv².'),
  ('physics', 'potential energy', 'thế năng', 'noun', 'Stored energy due to position or shape.', 'Năng lượng dự trữ do vị trí hoặc hình dạng.', 'A raised book has gravitational potential energy.', 'Quyển sách được nâng lên có thế năng trọng trường.'),
  ('physics', 'electric current', 'dòng điện', 'noun', 'The flow of electric charge.', 'Dòng chuyển dời có hướng của các điện tích.', 'Electric current is measured in amperes.', 'Cường độ dòng điện đo bằng ampe.'),
  ('physics', 'voltage', 'hiệu điện thế', 'noun', 'The difference in electric potential between two points.', 'Chênh lệch điện thế giữa hai điểm.', 'A phone charger supplies a voltage of 5 V.', 'Sạc điện thoại cấp hiệu điện thế 5 V.'),
  ('physics', 'resistance', 'điện trở', 'noun', 'How strongly a material opposes electric current.', 'Mức cản trở dòng điện của vật dẫn.', 'Resistance is measured in ohms.', 'Điện trở đo bằng ôm.'),
  ('physics', 'wavelength', 'bước sóng', 'noun', 'The distance between two neighbouring crests of a wave.', 'Khoảng cách giữa hai đỉnh sóng liền kề.', 'Red light has a longer wavelength than blue light.', 'Ánh sáng đỏ có bước sóng dài hơn ánh sáng lam.'),
  ('physics', 'frequency', 'tần số', 'noun', 'The number of oscillations per second.', 'Số dao động trong một giây.', 'Frequency is measured in hertz.', 'Tần số đo bằng héc.'),
  ('physics', 'pressure', 'áp suất', 'noun', 'Force acting on a unit of area.', 'Lực tác dụng lên một đơn vị diện tích.', 'Pressure increases with depth in water.', 'Áp suất tăng theo độ sâu trong nước.'),
  -- Chemistry
  ('chemistry', 'atom', 'nguyên tử', 'noun', 'The smallest particle of an element that keeps its chemical properties.', 'Hạt nhỏ nhất của nguyên tố còn giữ tính chất hoá học.', 'A water molecule has three atoms.', 'Một phân tử nước có ba nguyên tử.'),
  ('chemistry', 'molecule', 'phân tử', 'noun', 'Two or more atoms bonded together.', 'Hai hay nhiều nguyên tử liên kết với nhau.', 'O₂ is a molecule of oxygen.', 'O₂ là một phân tử oxi.'),
  ('chemistry', 'element', 'nguyên tố hoá học', 'noun', 'A substance made of only one kind of atom.', 'Chất chỉ gồm một loại nguyên tử.', 'Iron is an element with symbol Fe.', 'Sắt là nguyên tố có kí hiệu Fe.'),
  ('chemistry', 'compound', 'hợp chất', 'noun', 'A substance of two or more elements chemically combined.', 'Chất tạo bởi hai hay nhiều nguyên tố kết hợp hoá học.', 'Table salt is the compound NaCl.', 'Muối ăn là hợp chất NaCl.'),
  ('chemistry', 'mole', 'mol', 'noun', 'The amount of substance containing about 6.02 × 10²³ particles.', 'Lượng chất chứa khoảng 6,02 × 10²³ hạt.', 'One mole of water weighs 18 g.', 'Một mol nước nặng 18 g.'),
  ('chemistry', 'chemical reaction', 'phản ứng hoá học', 'noun', 'A process that turns substances into new substances.', 'Quá trình biến đổi chất này thành chất khác.', 'Burning wood is a chemical reaction.', 'Đốt gỗ là một phản ứng hoá học.'),
  ('chemistry', 'oxidation', 'sự oxi hoá', 'noun', 'The loss of electrons by a substance.', 'Quá trình một chất nhường electron.', 'Rusting is the oxidation of iron.', 'Gỉ sắt là sự oxi hoá của sắt.'),
  ('chemistry', 'acid', 'axit', 'noun', 'A substance that releases H⁺ ions in water; pH below 7.', 'Chất phân li ra ion H⁺ trong nước; pH nhỏ hơn 7.', 'Lemon juice contains citric acid.', 'Nước chanh chứa axit xitric.'),
  ('chemistry', 'base', 'bazơ', 'noun', 'A substance that releases OH⁻ ions in water; pH above 7.', 'Chất phân li ra ion OH⁻ trong nước; pH lớn hơn 7.', 'Sodium hydroxide is a strong base.', 'Natri hiđroxit là một bazơ mạnh.'),
  ('chemistry', 'catalyst', 'chất xúc tác', 'noun', 'A substance that speeds up a reaction without being used up.', 'Chất làm tăng tốc độ phản ứng mà không bị tiêu hao.', 'Enzymes are biological catalysts.', 'Enzim là chất xúc tác sinh học.'),
  ('chemistry', 'ion', 'ion', 'noun', 'An atom or group of atoms with an electric charge.', 'Nguyên tử hoặc nhóm nguyên tử mang điện tích.', 'Na⁺ is a positive ion.', 'Na⁺ là một ion dương.'),
  ('chemistry', 'solution', 'dung dịch', 'noun', 'A uniform mixture of a solute dissolved in a solvent.', 'Hỗn hợp đồng nhất của chất tan trong dung môi.', 'Salt water is a solution.', 'Nước muối là một dung dịch.'),
  -- Biology
  ('biology', 'cell', 'tế bào', 'noun', 'The basic unit of structure and function of living things.', 'Đơn vị cấu trúc và chức năng cơ bản của sinh vật.', 'Bacteria are made of a single cell.', 'Vi khuẩn chỉ gồm một tế bào.'),
  ('biology', 'gene', 'gen', 'noun', 'A segment of DNA that carries information for a trait.', 'Đoạn ADN mang thông tin quy định một tính trạng.', 'Eye colour is controlled by genes.', 'Màu mắt do gen quy định.'),
  ('biology', 'DNA', 'ADN', 'noun', 'The molecule that stores genetic information.', 'Phân tử lưu trữ thông tin di truyền.', 'DNA has a double-helix shape.', 'ADN có cấu trúc xoắn kép.'),
  ('biology', 'chromosome', 'nhiễm sắc thể', 'noun', 'A thread-like structure of DNA and proteins in the nucleus.', 'Cấu trúc dạng sợi gồm ADN và prôtêin trong nhân tế bào.', 'Human cells have 46 chromosomes.', 'Tế bào người có 46 nhiễm sắc thể.'),
  ('biology', 'photosynthesis', 'quang hợp', 'noun', 'The process plants use to make glucose from light, water and CO₂.', 'Quá trình cây dùng ánh sáng, nước và CO₂ để tạo glucôzơ.', 'Photosynthesis happens in chloroplasts.', 'Quang hợp diễn ra ở lục lạp.'),
  ('biology', 'cellular respiration', 'hô hấp tế bào', 'noun', 'The process that releases energy from food in cells.', 'Quá trình giải phóng năng lượng từ chất dinh dưỡng trong tế bào.', 'Cellular respiration produces ATP.', 'Hô hấp tế bào tạo ra ATP.'),
  ('biology', 'mitosis', 'nguyên phân', 'noun', 'Cell division that gives two identical daughter cells.', 'Sự phân bào tạo hai tế bào con giống hệt nhau.', 'Skin heals by mitosis.', 'Da lành lại nhờ nguyên phân.'),
  ('biology', 'meiosis', 'giảm phân', 'noun', 'Cell division that halves the chromosome number to make gametes.', 'Sự phân bào làm giảm một nửa số nhiễm sắc thể để tạo giao tử.', 'Meiosis produces egg and sperm cells.', 'Giảm phân tạo ra trứng và tinh trùng.'),
  ('biology', 'enzyme', 'enzim', 'noun', 'A protein that speeds up chemical reactions in living things.', 'Prôtêin làm tăng tốc phản ứng hoá học trong cơ thể sống.', 'Amylase is an enzyme that digests starch.', 'Amilaza là enzim tiêu hoá tinh bột.'),
  ('biology', 'mutation', 'đột biến', 'noun', 'A change in the DNA sequence.', 'Sự thay đổi trong trình tự ADN.', 'Some mutations cause genetic diseases.', 'Một số đột biến gây bệnh di truyền.'),
  ('biology', 'ecosystem', 'hệ sinh thái', 'noun', 'Living things and their environment interacting as a system.', 'Quần xã sinh vật cùng môi trường sống, tương tác như một hệ thống.', 'A mangrove forest is an ecosystem.', 'Rừng ngập mặn là một hệ sinh thái.'),
  ('biology', 'evolution', 'tiến hoá', 'noun', 'The change in inherited traits of populations over generations.', 'Sự thay đổi đặc điểm di truyền của quần thể qua các thế hệ.', 'Natural selection drives evolution.', 'Chọn lọc tự nhiên thúc đẩy tiến hoá.')
)
insert into public.terms (subject_id, term_en, term_vi, part_of_speech, definition_en, definition_vi, example_en, example_vi)
select s.id, src.term_en, src.term_vi, src.pos, src.def_en, src.def_vi, src.ex_en, src.ex_vi
from src join public.subjects s on s.slug = src.slug
on conflict (subject_id, lower(term_en)) do nothing;
